# SETUP
DefaultContentLanguage = "en"
baseurl = "http://www.peachepop.com/"
publishdir = "public"
#canonifyUrls = "true"
summaryLength = 15
[taxonomies]
category = "categories"
collection = "collections"
tag = "tags"
