# SETUP
DefaultContentLanguage = "en"
baseurl = "https://peachpop.netlify.app/"
publishdir = "public"
#canonifyUrls = "true"
summaryLength = 15
[taxonomies]
category = "categories"
collection = "collections"
tag = "tags"
