---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: data/profile.yaml
  label: Profile
- type: heading
  label: Website
- type: document
  path: data/appearance.yaml
  label: Appearance
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/shop
  label: Products
  create: documents
  match: "**/*"
  templates:
  - title-and-body
  - products
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog
  - title-and-body
upload_dir: pricilla-dettmer/peach-pop
public_path: https://res.cloudinary.com/hungryram19/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
