---
label: Products
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: sku
  type: text
  config:
    required: false
  label: SKU
- name: out_of_stock
  type: boolean
  label: Out of Stock
  description: Enable this to prevent adding product to cart
- name: price
  type: number
  label: Price
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: sale_price
  type: number
  label: Sale Price
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: collections
  type: tag_list
  default: []
  label: Collections
- name: photos
  type: image_gallery
  config: {}
  label: Photos
- name: customOptions
  type: blocks
  template_types:
  - simple-dropdown-option
  - text-option
  - text-block-option
  - question-block
  - advanced-dropdown-option
  config:
    min: 
    max: 
  label: Variants
pages:
- content/shop/calming.md
- content/shop/coco-butter.md
- content/shop/coco-lotion.md
- content/shop/green-pack.md
- content/shop/green-tea.md
